name: Build document
on: [push, create]
jobs:
  make-document:
    name: Compile document
    runs-on: ubuntu-latest
    container:
      image: k4zuki/pandocker-alpine:2.19
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup safe directory for git
        run: |
            repo=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}
            git config --global --add safe.directory /__w/${repo}/${repo}
      - name: Update dependencies
        run: |
            pip3 install pandocker-lua-filters docx-coreprop-writer
            pip3 install git+https://github.com/k4zuki/pandoc_misc.git@2.16.2
      - name: Set env
        run: |
            echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
            echo "DOWNLOAD_URL_BASE=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download" >> $GITHUB_ENV
      - name: Prepare QR code for this build (at a tag)
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        run: |
            pip3 install qrcode
            make initdir html
            TARGET=`ls Out/*.html`
            TARGET=${TARGET#Out/}
            echo "TARGET=${TARGET//.html/}" >> $GITHUB_ENV
      - name: Build document
        run: |
            qr ${{ env.DOWNLOAD_URL_BASE }}/${{ env.RELEASE_VERSION }}/${TARGET//.html/}.pdf > images/QRcode.png
            make initdir html docx pdf
      - name: Upload artifact files (at a push)
        uses: actions/upload-artifact@v3
        with:
          path: Out
